Introducing a lot of changes. Beware OKAPI-857, as this is an issue with this fork!

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,88 +1,86 @@
-#!/bin/bash -e
+#!/bin/sh
+# postinst script for folio-okapi
 #
-# This script is executed in the post-installation phase
-#
-#   On Debian,
-#       $1=configure : is set to 'configure' and if $2 is set, it is an upgrade
-#
+# see: dh_installdeb(1)
 
-# Sets the default values for okapi variables used in this script
-OKAPI_USER="okapi"
-OKAPI_GROUP="okapi"
-DATA_DIR="/var/lib/okapi"
-CONF_DIR="/etc/folio/okapi"
-LOG_DIR="/var/log/folio/okapi"
-LIB_DIR="/usr/share/folio/okapi/lib"
+set -e
 
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-# Source the default env file
-OKAPI_ENV_FILE="/etc/default/okapi"
-if [ -f "$OKAPI_ENV_FILE" ]; then
-    . "$OKAPI_ENV_FILE"
-fi
-
-OKAPI_CONF_FILE="${CONF_DIR}/okapi.conf"
-
-if [ -f "$OKAPI_CONF_FILE" ]; then
-    . "$OKAPI_CONF_FILE"
-else
-    echo "Cannot locate okapi.conf"
-    exit 2 
-fi
-
-
-IS_UPGRADE=false
 
 case "$1" in
+  configure)
+    # Make sure the user exists
+    if ! getent passwd folio-okapi > /dev/null
+      then
+        adduser --system --quiet --home /var/lib/folio/okapi --no-create-home \
+          --shell /bin/false --group --gecos "FOLIO central node" folio-okapi
+    fi
+    # If the user was created manually, make sure the group is there as well
+    if ! getent group folio-okapi > /dev/null
+      then
+        addgroup --system $quiet folio-okapi
+    fi
+    # Make sure user is in the group
+    if ! id -Gn folio-okapi | grep -qw folio-okapi
+      then
+        adduser $quiet folio-okapi folio-okapi
+    fi
 
-    configure)
-        # If $1=configure and $2 is set, this is an upgrade
-        if [ "$2" ]; then
-            IS_UPGRADE=true
-        fi
-    ;;
-    abort-upgrade|abort-remove|abort-deconfigure)
-    ;;
-
-    *)
-        echo "post install script called with unknown argument \`$1'" >&2
+    # Check validity of user and group
+    if [ "$(id -u folio-okapi)" = "0" ]
+      then
+        echo "The FOLIO central node user must not have uid 0 (root).
+Please fix this and reinstall this package." >&2
         exit 1
+    fi
+    if [ "$(id -g folio-okapi)" = "0" ]
+      then
+        echo "The FOLIO central node user must not have root as primary group.
+Please fix this and reinstall this package." >&2
+        exit 1
+    fi
+
+    # Create home directory & if neccessary 
+    mkdir -p /var/lib/folio/okapi
+    chown folio-okapi:folio-okapi /var/lib/folio/okapi
+
+    # create logdir - note: this should agree with logpath in service file
+    if [ ! -d /var/log/folio/okapi ]
+      then
+        mkdir -p /var/log/folio/okapi
+        chown folio-okapi:adm /var/log/folio/okapi
+    fi
+
+    # create a config file
+    if [ ! -f /etc/folio/okapi/okapi.conf ]
+      then
+        /usr/share/folio/okapi/bin/setup_okapi.sh
+    fi
+    ;;
+
+  abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+  *)
+    echo "postinst called with unknown argument \`$1'" >&2
+    exit 1
     ;;
 esac
 
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
-mkdir -p "$LOG_DIR"
-chown -R ${OKAPI_USER}.${OKAPI_GROUP} $LOG_DIR
-chown -R root.${OKAPI_GROUP} $CONF_DIR
-chmod 0755 $CONF_DIR
-
-
-if [ "$IS_UPGRADE" != "true" ]; then
-    # initial installation.  configure systemd and start okapi
-    if command -v systemctl >/dev/null; then
-        echo "Configuring Okapi service..."
-        systemctl enable okapi.service
-        systemctl daemon-reload
-        echo -n "Starting Okapi..."       
-        systemctl start okapi.service || true
-        echo " OK"
-    fi
-
-elif [ "$RESTART_ON_UPGRADE" = "true" ]; then
-    # okapi upgrade and RESTART_ON_UPGRADE="true"
-    echo -n "Restarting okapi service..."
-    if command -v systemctl >/dev/null; then
-        systemctl daemon-reload
-        systemctl restart okapi.service || true
-        echo " OK"
-    fi
-else 
-    # okapi upgrade and RESTART_ON_UPGRADE is false or not set.
-    echo "Okapi upgraded but not restarted. To restart Okapi:"
-    echo "   sudo systemctl daemon-reload"
-    echo "   sudo systemctl restart okapi.service" 
-    echo ""
-fi
+#DEBHELPER#
 
 exit 0
-
